import { COLORS } from './constants'

export const Styles = {
  page: {
    minHeight: '100vh',
    background: COLORS.bg,
    fontFamily: "'Inter',system-ui,-apple-system,sans-serif",
    color: COLORS.text,
  },
  header: {
    background: 'var(--t-bg)',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    padding: '0 28px',
    height: 60,
    position: 'sticky' as const,
    top: 0,
    zIndex: 100,
    boxShadow: '0 2px 16px rgba(0,0,0,.35)',
  },
  logoMark: {
    fontWeight: 800,
    fontSize: 14,
    color: COLORS.white,
    background: COLORS.blue,
    padding: '4px 8px',
    borderRadius: 3,
    letterSpacing: -0.5,
    marginRight: 10,
  },
  logoText: {
    fontWeight: 600,
    fontSize: 13,
    color: '#b0bcd0',
    letterSpacing: 0.5,
  },
  badge: {
    fontFamily: 'monospace',
    fontSize: 11,
    background: 'color-mix(in srgb, var(--t-text) 8%, transparent)',
    color: 'var(--t-muted)',
    padding: '4px 10px',
    borderRadius: 2,
    border: '1px solid color-mix(in srgb, var(--t-text) 10%, transparent)',
  },
  langBtn: {
    fontSize: 11,
    fontWeight: 700,
    padding: '4px 9px',
    borderRadius: 2,
    border: '1px solid color-mix(in srgb, var(--t-text) 15%, transparent)',
    cursor: 'pointer',
    fontFamily: 'monospace',
    letterSpacing: 0.5,
    transition: 'all .15s',
  },
  input: {
    width: '100%',
    height: 44,
    border: `1.5px solid ${COLORS.border}`,
    borderRadius: 4,
    background: 'var(--t-card-bg)',
    fontFamily: 'inherit',
    fontSize: 14,
    color: COLORS.text,
    padding: '0 14px',
    outline: 'none',
  },
  label: {
    display: 'block',
    fontSize: 12,
    fontWeight: 700,
    color: COLORS.text,
    marginBottom: 6,
  },
  breadcrumb: {
    fontFamily: 'monospace',
    fontSize: 11,
    color: COLORS.muted,
    marginBottom: 28,
  },
  card: {
    background: 'var(--t-card-bg)',
    border: `1px solid ${COLORS.border}`,
    borderRadius: 8,
    boxShadow: '0 4px 24px rgba(0,0,0,.06)',
  },
  cardHeader: {
    background: `linear-gradient(135deg,${COLORS.navy} 0%,${COLORS.navy2} 100%)`,
    padding: '24px 28px',
    display: 'flex',
    alignItems: 'center',
    gap: 14,
  },
  btnPrimary: (bg: string = COLORS.blue) => ({
    background: bg,
    color: COLORS.white,
    fontWeight: 700,
    fontSize: 14,
    padding: '12px 30px',
    borderRadius: 4,
    border: 'none',
    cursor: 'pointer',
    boxShadow: `0 4px 16px color-mix(in srgb, ${bg} 27%, transparent)`,
  }),
  btnOutline: {
    padding: '9px 20px',
    borderRadius: 4,
    border: `1.5px solid ${COLORS.border}`,
    background: 'var(--t-card-bg)',
    fontSize: 13,
    fontWeight: 600,
    cursor: 'pointer',
  },
  btnGhost: {
    background: 'none',
    border: 'none',
    color: COLORS.muted,
    fontSize: 14,
    cursor: 'pointer',
    display: 'flex',
    alignItems: 'center',
    gap: 6,
  },
}
