-- 1. Create public.questions table if not exists
CREATE TABLE IF NOT EXISTS public.questions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  topic TEXT NOT NULL,
  topic_key TEXT,
  text TEXT NOT NULL,
  text_ru TEXT,
  opts TEXT[] NOT NULL,
  opts_ru TEXT[],
  correct INT NOT NULL,
  exam_type TEXT NOT NULL DEFAULT 'all',
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Enable RLS and grants on questions
ALTER TABLE public.questions ENABLE ROW LEVEL SECURITY;
GRANT ALL ON public.questions TO anon, authenticated, service_role;

DROP POLICY IF EXISTS "Allow anon select questions" ON public.questions;
DROP POLICY IF EXISTS "Allow anon insert questions" ON public.questions;
DROP POLICY IF EXISTS "Allow anon update questions" ON public.questions;
DROP POLICY IF EXISTS "Allow anon delete questions" ON public.questions;

CREATE POLICY "Allow anon select questions" ON public.questions FOR SELECT TO anon USING (true);
CREATE POLICY "Allow anon insert questions" ON public.questions FOR INSERT TO anon WITH CHECK (true);
CREATE POLICY "Allow anon update questions" ON public.questions FOR UPDATE TO anon USING (true) WITH CHECK (true);
CREATE POLICY "Allow anon delete questions" ON public.questions FOR DELETE TO anon USING (true);

-- 2. Create public.exams table
CREATE TABLE IF NOT EXISTS public.exams (
  id TEXT PRIMARY KEY,
  title_en TEXT NOT NULL,
  title_ru TEXT NOT NULL,
  description_en TEXT,
  description_ru TEXT,
  subject TEXT NOT NULL DEFAULT 'math',
  time_limit_sec INT NOT NULL DEFAULT 3600,
  is_active BOOLEAN NOT NULL DEFAULT true,
  require_parent_info BOOLEAN NOT NULL DEFAULT false,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Enable RLS and policies on exams
ALTER TABLE public.exams ENABLE ROW LEVEL SECURITY;
GRANT ALL ON public.exams TO anon, authenticated, service_role;

DROP POLICY IF EXISTS "Allow anon select exams" ON public.exams;
DROP POLICY IF EXISTS "Allow anon insert exams" ON public.exams;
DROP POLICY IF EXISTS "Allow anon update exams" ON public.exams;
DROP POLICY IF EXISTS "Allow anon delete exams" ON public.exams;

CREATE POLICY "Allow anon select exams" ON public.exams FOR SELECT TO anon USING (true);
CREATE POLICY "Allow anon insert exams" ON public.exams FOR INSERT TO anon WITH CHECK (true);
CREATE POLICY "Allow anon update exams" ON public.exams FOR UPDATE TO anon USING (true) WITH CHECK (true);
CREATE POLICY "Allow anon delete exams" ON public.exams FOR DELETE TO anon USING (true);

-- 3. Alter public.questions to add exam_id link referencing exams
ALTER TABLE public.questions ADD COLUMN IF NOT EXISTS exam_id TEXT REFERENCES public.exams(id) ON DELETE CASCADE;
